In [1]:
import pandas as pd
import numpy as np

input_df = pd.read_parquet("datasets/daily_total_sales.parquet")
input_df

,datetime,total_sales,day_of_week,month,is_weekend,lag_1,lag_7,rolling_mean_7
0,2017-01-09,67364.489004,0,1,0,83868.925011,92116.733997,77144.313428
1,2017-01-10,57878.826959,1,1,0,67364.489004,82144.183962,73677.833856
2,2017-01-11,67498.498082,2,1,0,57878.826959,83542.260046,71385.867861
3,2017-01-12,51648.812997,3,1,0,67498.498082,63309.811987,69720.010862
4,2017-01-13,68828.135029,4,1,0,51648.812997,75487.895984,68768.616440
...,...,...,...,...,...,...,...,...
168,2017-06-26,56422.055035,0,6,0,77040.755990,59910.121978,64084.486579
169,2017-06-27,51423.170007,1,6,0,56422.055035,60942.420006,62724.593722
170,2017-06-28,62261.489035,2,6,0,51423.170007,65345.439019,62284.029439
171,2017-06-29,48412.346025,3,6,0,62261.489035,49417.084986,62140.495302
172,2017-06-30,63262.708989,4,6,0,48412.346025,64655.015982,61941.594303

In [2]:
input_df["target"] = input_df["total_sales"].shift(-1)
input_df = input_df.dropna().reset_index(drop=True)
input_df

,datetime,total_sales,day_of_week,month,is_weekend,lag_1,lag_7,rolling_mean_7,target
0,2017-01-09,67364.489004,0,1,0,83868.925011,92116.733997,77144.313428,57878.826959
1,2017-01-10,57878.826959,1,1,0,67364.489004,82144.183962,73677.833856,67498.498082
2,2017-01-11,67498.498082,2,1,0,57878.826959,83542.260046,71385.867861,51648.812997
3,2017-01-12,51648.812997,3,1,0,67498.498082,63309.811987,69720.010862,68828.135029
4,2017-01-13,68828.135029,4,1,0,51648.812997,75487.895984,68768.616440,81638.096985
...,...,...,...,...,...,...,...,...,...
167,2017-06-25,77040.755990,6,6,1,74768.635037,62433.863008,64582.781857,56422.055035
168,2017-06-26,56422.055035,0,6,0,77040.755990,59910.121978,64084.486579,51423.170007
169,2017-06-27,51423.170007,1,6,0,56422.055035,60942.420006,62724.593722,62261.489035
170,2017-06-28,62261.489035,2,6,0,51423.170007,65345.439019,62284.029439,48412.346025
171,2017-06-29,48412.346025,3,6,0,62261.489035,49417.084986,62140.495302,63262.708989

In [8]:
feature_cols = input_df.columns.drop(["target"])
feature_cols

Index(['datetime', 'total_sales', 'day_of_week', 'month', 'is_weekend',
       'lag_1', 'lag_7', 'rolling_mean_7'],
      dtype='object')

In [5]:
split_idx = int(len(input_df) * 0.8)
train_df = input_df.iloc[:split_idx]
test_df = input_df.iloc[split_idx:]

In [6]:
train_df.shape

(137, 9)

In [7]:
test_df.shape

(35, 9)

In [9]:
train_df.head()

,datetime,total_sales,day_of_week,month,is_weekend,lag_1,lag_7,rolling_mean_7,target
0,2017-01-09,67364.489004,0,1,0,83868.925011,92116.733997,77144.313428,57878.826959
1,2017-01-10,57878.826959,1,1,0,67364.489004,82144.183962,73677.833856,67498.498082
2,2017-01-11,67498.498082,2,1,0,57878.826959,83542.260046,71385.867861,51648.812997
3,2017-01-12,51648.812997,3,1,0,67498.498082,63309.811987,69720.010862,68828.135029
4,2017-01-13,68828.135029,4,1,0,51648.812997,75487.895984,68768.616440,81638.096985

In [10]:
test_df.head()

,datetime,total_sales,day_of_week,month,is_weekend,lag_1,lag_7,rolling_mean_7,target
137,2017-05-26,66857.272957,4,5,0,50866.386002,61768.318019,64245.694165,64975.386003
138,2017-05-27,64975.386003,5,5,1,66857.272957,77076.105035,62517.020017,66963.014047
139,2017-05-28,66963.014047,6,5,1,64975.386003,82892.873081,60241.325869,58001.266986
140,2017-05-29,58001.266986,0,5,0,66963.014047,59061.920045,60089.804004,53768.769046
141,2017-05-30,53768.769046,1,5,0,58001.266986,51037.604005,60479.970438,67443.445985